CC=gcc
CFLAGS=-framework OpenGL -framework GLUT
EXEC=ativ1
OBJ=ativ1.o
all: $(EXEC)
ativ1: 
	g++ igreja.cpp  -w -framework CoreFoundation -framework OpenGL -framework GLUT -o igreja -stdlib=libc++ -std=c++11 -lsfml-graphics -lsfml-window -lsfml-system
